### ISSUE TITLE
添加管理功能支持

### ISSUE THREAD

**Issue by Linnest2020** [OlivOS-Team/ChanceCustom#23]
旧铃心插件含有【禁言】等管理功能, 应当兼容。

**Comment by lunzhiPenxil** [comment]
已将该需求的优先级提前

**Comment by Linnest2020** [comment]
等我有空pr一个？

**Comment by Linnest2020** [comment]
在本人分支的[新提交](https://github.com/Linnest2020/ChanceCustom/commit/125e27a6cf7d3b37fcd9f8727d38fc24cf7ac1fb)中已经实现了禁言功能, 但是实现的方法是使用了[通用的Currying装饰器](https://github.com/Linnest2020/ChanceCustom/blob/125e27a6cf7d3b37fcd9f8727d38fc24cf7ac1fb/ChanceCustom/replyAuth.py#L27-L42), 请谨慎考虑
